-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 11:49:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pokemons_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pokemons_id` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pokeOne` INT NULL,
  `pokeTwo` INT NULL,
  `PokeThree` INT NULL,
  `pokeFour` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pokemons_with_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pokemons_with_users` (
  `users_id` INT NOT NULL,
  `pokemons_id_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `pokemons_id_id`),
  INDEX `fk_pokemons_with_users_pokemons_id1_idx` (`pokemons_id_id` ASC) VISIBLE,
  CONSTRAINT `fk_pokemons_with_users_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemons_with_users_pokemons_id1`
    FOREIGN KEY (`pokemons_id_id`)
    REFERENCES `mydb`.`pokemons_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
